"""
nuc.periodic_table — table des 118 éléments (symbole, nom français),
extraite programmatiquement de Lara.cpp (G. Dougniaux, 2012) — voir
docs/RECONCILIATION.md §5.
"""

ELEMENTS = [  # index 0 -> Z=1 (H)
    {"Z": 1, "symbol": 'H', "name_fr": 'Hydrogène'},
    {"Z": 2, "symbol": 'He', "name_fr": 'Hélium'},
    {"Z": 3, "symbol": 'Li', "name_fr": 'Lithium'},
    {"Z": 4, "symbol": 'Be', "name_fr": 'Béryllium'},
    {"Z": 5, "symbol": 'B', "name_fr": 'Bore'},
    {"Z": 6, "symbol": 'C', "name_fr": 'Carbone'},
    {"Z": 7, "symbol": 'N', "name_fr": 'Azote'},
    {"Z": 8, "symbol": 'O', "name_fr": 'Oxygène'},
    {"Z": 9, "symbol": 'F', "name_fr": 'Fluor'},
    {"Z": 10, "symbol": 'Ne', "name_fr": 'Néon'},
    {"Z": 11, "symbol": 'Na', "name_fr": 'Sodium'},
    {"Z": 12, "symbol": 'Mg', "name_fr": 'Magnésium'},
    {"Z": 13, "symbol": 'Al', "name_fr": 'Aluminium'},
    {"Z": 14, "symbol": 'Si', "name_fr": 'Silicium'},
    {"Z": 15, "symbol": 'P', "name_fr": 'Phosphore'},
    {"Z": 16, "symbol": 'S', "name_fr": 'Soufre'},
    {"Z": 17, "symbol": 'Cl', "name_fr": 'Chlore'},
    {"Z": 18, "symbol": 'Ar', "name_fr": 'Argon'},
    {"Z": 19, "symbol": 'K', "name_fr": 'Potassium'},
    {"Z": 20, "symbol": 'Ca', "name_fr": 'Calcium'},
    {"Z": 21, "symbol": 'Sc', "name_fr": 'Scandium'},
    {"Z": 22, "symbol": 'Ti', "name_fr": 'Titane'},
    {"Z": 23, "symbol": 'V', "name_fr": 'Vanadium'},
    {"Z": 24, "symbol": 'Cr', "name_fr": 'Chrome'},
    {"Z": 25, "symbol": 'Mn', "name_fr": 'Manganèse'},
    {"Z": 26, "symbol": 'Fe', "name_fr": 'Fer'},
    {"Z": 27, "symbol": 'Co', "name_fr": 'Cobalt'},
    {"Z": 28, "symbol": 'Ni', "name_fr": 'Nickel'},
    {"Z": 29, "symbol": 'Cu', "name_fr": 'Cuivre'},
    {"Z": 30, "symbol": 'Zn', "name_fr": 'Zinc'},
    {"Z": 31, "symbol": 'Ga', "name_fr": 'Gallium'},
    {"Z": 32, "symbol": 'Ge', "name_fr": 'Germanium'},
    {"Z": 33, "symbol": 'As', "name_fr": 'Arsenic'},
    {"Z": 34, "symbol": 'Se', "name_fr": 'Sélénium'},
    {"Z": 35, "symbol": 'Br', "name_fr": 'Brome'},
    {"Z": 36, "symbol": 'Kr', "name_fr": 'Krypton'},
    {"Z": 37, "symbol": 'Rb', "name_fr": 'Rubidium'},
    {"Z": 38, "symbol": 'Sr', "name_fr": 'Strontium'},
    {"Z": 39, "symbol": 'Y', "name_fr": 'Yttrium'},
    {"Z": 40, "symbol": 'Zr', "name_fr": 'Zirconium'},
    {"Z": 41, "symbol": 'Nb', "name_fr": 'Niobium'},
    {"Z": 42, "symbol": 'Mo', "name_fr": 'Molybdène'},
    {"Z": 43, "symbol": 'Tc', "name_fr": 'Technétium'},
    {"Z": 44, "symbol": 'Ru', "name_fr": 'Ruthérium'},
    {"Z": 45, "symbol": 'Rh', "name_fr": 'Rhodium'},
    {"Z": 46, "symbol": 'Pd', "name_fr": 'Palladium'},
    {"Z": 47, "symbol": 'Ag', "name_fr": 'Argent'},
    {"Z": 48, "symbol": 'Cd', "name_fr": 'Cadmium'},
    {"Z": 49, "symbol": 'In', "name_fr": 'Indium'},
    {"Z": 50, "symbol": 'Sn', "name_fr": 'Etain'},
    {"Z": 51, "symbol": 'Sb', "name_fr": 'Antimoine'},
    {"Z": 52, "symbol": 'Te', "name_fr": 'Tellure'},
    {"Z": 53, "symbol": 'I', "name_fr": 'Iode'},
    {"Z": 54, "symbol": 'Xe', "name_fr": 'Xénon'},
    {"Z": 55, "symbol": 'Cs', "name_fr": 'Césium'},
    {"Z": 56, "symbol": 'Ba', "name_fr": 'Baryum'},
    {"Z": 57, "symbol": 'La', "name_fr": 'Lanthane'},
    {"Z": 58, "symbol": 'Ce', "name_fr": 'Cérium'},
    {"Z": 59, "symbol": 'Pr', "name_fr": 'Praséodyme'},
    {"Z": 60, "symbol": 'Nd', "name_fr": 'Néodyme'},
    {"Z": 61, "symbol": 'Pm', "name_fr": 'Prométhium'},
    {"Z": 62, "symbol": 'Sm', "name_fr": 'Samarium'},
    {"Z": 63, "symbol": 'Eu', "name_fr": 'Europium'},
    {"Z": 64, "symbol": 'Gd', "name_fr": 'Gadolinium'},
    {"Z": 65, "symbol": 'Tb', "name_fr": 'Terbium'},
    {"Z": 66, "symbol": 'Dy', "name_fr": 'Dysprosium'},
    {"Z": 67, "symbol": 'Ho', "name_fr": 'Holmium'},
    {"Z": 68, "symbol": 'Er', "name_fr": 'Erbium'},
    {"Z": 69, "symbol": 'Tm', "name_fr": 'Thullium'},
    {"Z": 70, "symbol": 'Yb', "name_fr": 'Ytterbium'},
    {"Z": 71, "symbol": 'Lu', "name_fr": 'Lutécium'},
    {"Z": 72, "symbol": 'Hf', "name_fr": 'Hafnium'},
    {"Z": 73, "symbol": 'Ta', "name_fr": 'Tantale'},
    {"Z": 74, "symbol": 'W', "name_fr": 'Tungstène'},
    {"Z": 75, "symbol": 'Re', "name_fr": 'Rhénium'},
    {"Z": 76, "symbol": 'Os', "name_fr": 'Osmium'},
    {"Z": 77, "symbol": 'Ir', "name_fr": 'Iridium'},
    {"Z": 78, "symbol": 'Pt', "name_fr": 'Platine'},
    {"Z": 79, "symbol": 'Au', "name_fr": 'Or'},
    {"Z": 80, "symbol": 'Hg', "name_fr": 'Mercure'},
    {"Z": 81, "symbol": 'Tl', "name_fr": 'Thallium'},
    {"Z": 82, "symbol": 'Pb', "name_fr": 'Plomb'},
    {"Z": 83, "symbol": 'Bi', "name_fr": 'Bismuth'},
    {"Z": 84, "symbol": 'Po', "name_fr": 'Polonium'},
    {"Z": 85, "symbol": 'At', "name_fr": 'Astate'},
    {"Z": 86, "symbol": 'Rn', "name_fr": 'Radon'},
    {"Z": 87, "symbol": 'Fr', "name_fr": 'Francium'},
    {"Z": 88, "symbol": 'Ra', "name_fr": 'Radium'},
    {"Z": 89, "symbol": 'Ac', "name_fr": 'Actinium'},
    {"Z": 90, "symbol": 'Th', "name_fr": 'Thorium'},
    {"Z": 91, "symbol": 'Pa', "name_fr": 'Protactinium'},
    {"Z": 92, "symbol": 'U', "name_fr": 'Uranium'},
    {"Z": 93, "symbol": 'Np', "name_fr": 'Neptunium'},
    {"Z": 94, "symbol": 'Pu', "name_fr": 'Plutonium'},
    {"Z": 95, "symbol": 'Am', "name_fr": 'Américium'},
    {"Z": 96, "symbol": 'Cm', "name_fr": 'Curium'},
    {"Z": 97, "symbol": 'Bk', "name_fr": 'Berkélium'},
    {"Z": 98, "symbol": 'Cf', "name_fr": 'Californium'},
    {"Z": 99, "symbol": 'Es', "name_fr": 'Einsteinium'},
    {"Z": 100, "symbol": 'Fm', "name_fr": 'Fermium'},
    {"Z": 101, "symbol": 'Md', "name_fr": 'Mendélévium'},
    {"Z": 102, "symbol": 'No', "name_fr": 'Nobélium'},
    {"Z": 103, "symbol": 'Lr', "name_fr": 'Lawrencium'},
    {"Z": 104, "symbol": 'Rf', "name_fr": 'Rutherfordium'},
    {"Z": 105, "symbol": 'Db', "name_fr": 'Dubnium'},
    {"Z": 106, "symbol": 'Sg', "name_fr": 'Seaborgium'},
    {"Z": 107, "symbol": 'Bh', "name_fr": 'Bohrium'},
    {"Z": 108, "symbol": 'Hs', "name_fr": 'Hassium'},
    {"Z": 109, "symbol": 'Mt', "name_fr": 'Meitnérium'},
    {"Z": 110, "symbol": 'Ds', "name_fr": 'Darmstadtium'},
    {"Z": 111, "symbol": 'Rg', "name_fr": 'Roentgenium'},
    {"Z": 112, "symbol": 'Cn', "name_fr": 'Copernicium'},
    {"Z": 113, "symbol": 'Uut', "name_fr": 'Ununtrium'},
    {"Z": 114, "symbol": 'Fl', "name_fr": 'Flévorium'},
    {"Z": 115, "symbol": 'Uup', "name_fr": 'Ununpentium'},
    {"Z": 116, "symbol": 'Lv', "name_fr": 'Livermorium'},
    {"Z": 117, "symbol": 'Uus', "name_fr": 'Ununseptium'},
    {"Z": 118, "symbol": 'Uuo', "name_fr": 'Ununoctium'},
]

_BY_SYMBOL = {e["symbol"]: e for e in ELEMENTS}
_BY_Z = {e["Z"]: e for e in ELEMENTS}


def z_of_symbol(symbol: str) -> int:
    """Numéro atomique Z à partir du symbole (ex. "Zr" -> 40). 0 si inconnu."""
    e = _BY_SYMBOL.get(symbol)
    return e["Z"] if e else 0


def symbol_of_z(z: int) -> str:
    """Symbole à partir de Z (ex. 40 -> "Zr")."""
    e = _BY_Z.get(z)
    return e["symbol"] if e else ""
