#include "nuc_periodic_table.h"
#include <string.h>

const nuc_element NUC_ELEMENTS[NUC_N_ELEMENTS] = {
    {1, "H", "Hydrogène"},
    {2, "He", "Hélium"},
    {3, "Li", "Lithium"},
    {4, "Be", "Béryllium"},
    {5, "B", "Bore"},
    {6, "C", "Carbone"},
    {7, "N", "Azote"},
    {8, "O", "Oxygène"},
    {9, "F", "Fluor"},
    {10, "Ne", "Néon"},
    {11, "Na", "Sodium"},
    {12, "Mg", "Magnésium"},
    {13, "Al", "Aluminium"},
    {14, "Si", "Silicium"},
    {15, "P", "Phosphore"},
    {16, "S", "Soufre"},
    {17, "Cl", "Chlore"},
    {18, "Ar", "Argon"},
    {19, "K", "Potassium"},
    {20, "Ca", "Calcium"},
    {21, "Sc", "Scandium"},
    {22, "Ti", "Titane"},
    {23, "V", "Vanadium"},
    {24, "Cr", "Chrome"},
    {25, "Mn", "Manganèse"},
    {26, "Fe", "Fer"},
    {27, "Co", "Cobalt"},
    {28, "Ni", "Nickel"},
    {29, "Cu", "Cuivre"},
    {30, "Zn", "Zinc"},
    {31, "Ga", "Gallium"},
    {32, "Ge", "Germanium"},
    {33, "As", "Arsenic"},
    {34, "Se", "Sélénium"},
    {35, "Br", "Brome"},
    {36, "Kr", "Krypton"},
    {37, "Rb", "Rubidium"},
    {38, "Sr", "Strontium"},
    {39, "Y", "Yttrium"},
    {40, "Zr", "Zirconium"},
    {41, "Nb", "Niobium"},
    {42, "Mo", "Molybdène"},
    {43, "Tc", "Technétium"},
    {44, "Ru", "Ruthérium"},
    {45, "Rh", "Rhodium"},
    {46, "Pd", "Palladium"},
    {47, "Ag", "Argent"},
    {48, "Cd", "Cadmium"},
    {49, "In", "Indium"},
    {50, "Sn", "Etain"},
    {51, "Sb", "Antimoine"},
    {52, "Te", "Tellure"},
    {53, "I", "Iode"},
    {54, "Xe", "Xénon"},
    {55, "Cs", "Césium"},
    {56, "Ba", "Baryum"},
    {57, "La", "Lanthane"},
    {58, "Ce", "Cérium"},
    {59, "Pr", "Praséodyme"},
    {60, "Nd", "Néodyme"},
    {61, "Pm", "Prométhium"},
    {62, "Sm", "Samarium"},
    {63, "Eu", "Europium"},
    {64, "Gd", "Gadolinium"},
    {65, "Tb", "Terbium"},
    {66, "Dy", "Dysprosium"},
    {67, "Ho", "Holmium"},
    {68, "Er", "Erbium"},
    {69, "Tm", "Thullium"},
    {70, "Yb", "Ytterbium"},
    {71, "Lu", "Lutécium"},
    {72, "Hf", "Hafnium"},
    {73, "Ta", "Tantale"},
    {74, "W", "Tungstène"},
    {75, "Re", "Rhénium"},
    {76, "Os", "Osmium"},
    {77, "Ir", "Iridium"},
    {78, "Pt", "Platine"},
    {79, "Au", "Or"},
    {80, "Hg", "Mercure"},
    {81, "Tl", "Thallium"},
    {82, "Pb", "Plomb"},
    {83, "Bi", "Bismuth"},
    {84, "Po", "Polonium"},
    {85, "At", "Astate"},
    {86, "Rn", "Radon"},
    {87, "Fr", "Francium"},
    {88, "Ra", "Radium"},
    {89, "Ac", "Actinium"},
    {90, "Th", "Thorium"},
    {91, "Pa", "Protactinium"},
    {92, "U", "Uranium"},
    {93, "Np", "Neptunium"},
    {94, "Pu", "Plutonium"},
    {95, "Am", "Américium"},
    {96, "Cm", "Curium"},
    {97, "Bk", "Berkélium"},
    {98, "Cf", "Californium"},
    {99, "Es", "Einsteinium"},
    {100, "Fm", "Fermium"},
    {101, "Md", "Mendélévium"},
    {102, "No", "Nobélium"},
    {103, "Lr", "Lawrencium"},
    {104, "Rf", "Rutherfordium"},
    {105, "Db", "Dubnium"},
    {106, "Sg", "Seaborgium"},
    {107, "Bh", "Bohrium"},
    {108, "Hs", "Hassium"},
    {109, "Mt", "Meitnérium"},
    {110, "Ds", "Darmstadtium"},
    {111, "Rg", "Roentgenium"},
    {112, "Cn", "Copernicium"},
    {113, "Uut", "Ununtrium"},
    {114, "Fl", "Flévorium"},
    {115, "Uup", "Ununpentium"},
    {116, "Lv", "Livermorium"},
    {117, "Uus", "Ununseptium"},
    {118, "Uuo", "Ununoctium"},
};

int nuc_z_of_symbol(const char *symbol) {
    for (int i = 0; i < NUC_N_ELEMENTS; i++)
        if (strcmp(NUC_ELEMENTS[i].symbol, symbol) == 0) return NUC_ELEMENTS[i].Z;
    return 0;
}

const char *nuc_symbol_of_z(int z) {
    if (z < 1 || z > NUC_N_ELEMENTS) return NULL;
    return NUC_ELEMENTS[z - 1].symbol;
}
